# Generated by Django 4.1.1 on 2022-10-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
